## CHANGE this to the name of your plugin.
name: MagicPowder

## CHANGE this to your username.
author: FramesEnd

## CHANGE this to a meaningful but short description of your plugin.
description: A Slimefun-4 Addon that adds... magic powders of many types.

## CHANGE this to the path of the class that extends JavaPlugin.
main: me.framesend.magicpowder.MagicPowder

## This value is automatically replaced by the version specified in your pom.xml file.
## Do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.14

## This is required and marks Slimefun as a plugin dependency.
depend:
- Slimefun